function [pks_pos, locs_pos, pks_neg, locs_neg] = myFindColPeaks(dat)
    dat_mean = mean( dat);
    dat_std = std( dat);
    [pks_pos, locs_pos, w_pos, p_pos] = findpeaks(dat,...
        'NPeaks', 6,...
        'MinPeakDistance',size(dat,1)/(6*2),...
        'MinPeakHeight', dat_mean + 3*dat_std);
    % figure; plot(im_module_sum_row_diff_lpf); hold on; plot(locs_pos, pks_pos,'O');
    % 负向
    % 注意两处负号
    [pks_neg, locs_neg, w_neg, p_neg] = findpeaks(-dat,...
        'NPeaks', 6,...
        'MinPeakDistance',size(dat,1)/(6*2),...
        'MinPeakHeight', dat_mean + 3*dat_std);
    pks_neg = -pks_neg;
end